### ISSUE TITLE
Feature Request: Add screen recording apps?

### ISSUE THREAD

**Issue by jackmcconnell** [bdkjones/MuzzleApp#1]
Sticking a muzzle on notifications when using screen recording apps would be awesome. 

As a feature request, please consider adding QuickTime, ScreenFlow, and Capto (as starting points) when in recording mode to Muzzles' capabilities.

Thanks!

**Comment by RobGibbens** [comment]
And Camtasia

**Comment by bdkjones** [comment]
It's already done. Give it a try.
