### ISSUE TITLE
App Icon Not Displaying in Taskbar - Mac OS 14.2.1 (23C71)

### ISSUE THREAD

**Issue by mattroark** [bdkjones/MuzzleApp#110]
Muzzle icon is not displaying in the Mac OS taskbar after upgrading to Mac OS 14.2.1. If I open the app manually via the CLI, I'm prompted with "Permission Required" even though Muzzle is already allowed under the Accessibility settings.

`open /Applications/Muzzle.app/Contents/MacOS/Muzzle`

**Comment by bdkjones** [comment]
You don’t need Muzzle on Sonoma; Apple baked the app into macOS starting with 12.0On Feb 5, 2024, at 08:48, Matt Roark ***@***.***> wrote:﻿
Muzzle icon is not displaying in the Mac OS taskbar after upgrading to Mac OS 14.2.1. If I open the app manually via the CLI, I'm prompted with "Permission Required" even though Muzzle is already allowed under the Accessibility settings.
open /Applications/Muzzle.app/Contents/MacOS/Muzzle
