### ISSUE TITLE
Uninstall Muzzle

### ISSUE THREAD

**Issue by heathcurtiss** [bdkjones/MuzzleApp#112]
I'd like to uninstall Muzzle, but it doesn't appear in the applications folder and it doesn't appear in Launchpad.  How do I do it?

**Comment by bdkjones** [comment]
You'd have to find the location where you installed the app. If you first ran the app from your /Downloads folder, macOS "translocated" the binary to a read-only volume buried inside system temporary folders. Muzzle might be running from that location. Googling "App Translocation" will turn up details about the process.

You can use Activity Monitor to pull up a list of open files for any process running on your Mac. Start there.

**Comment by heathcurtiss** [comment]
Yikes. I did install it from /Downloads.  I'll begin the googling.

**Comment by bdkjones** [comment]
Yea, always move apps to /Applications before running them for the first time. Otherwise macOS is gonna do weird things to protect you.
