### ISSUE TITLE
Support for Google Hangouts Meet

### ISSUE THREAD

**Issue by paulvantuyl** [bdkjones/MuzzleApp#15]
I know [Hangouts Meet](https://gsuite.google.com/products/meet/) has only recently been released, but we’re using it pretty heavily at my work and it would be killer to Muzzle it.

**Comment by bdkjones** [comment]
Have you tested it?

**Comment by paulvantuyl** [comment]
Yes, tested, DND is not activating.

**Comment by paulvantuyl** [comment]
Correction, it is working properly. I just re-tested and once screensharing starts, DND activates.

**Comment by bdkjones** [comment]
Yep. There's a brief 1 second delay for technical reasons.
