### ISSUE TITLE
No luck with Google Hangouts

### ISSUE THREAD

**Issue by paulwakeford** [bdkjones/MuzzleApp#16]
1. Verified DND was off.
2. I started a hangout from a Google Calendar link. It's GSuite for Business if that matters - URL format is https://hangouts.google.com/hangouts/_/companyname/hangoutname?authuser=0 if that matters.
3. Started screenshare.
4. DND is still off.
5. Started 'present to everyone'
6. DND still off.

Thanks,

Paul

**Comment by bdkjones** [comment]
Did you share your whole screen, or only one window or part of the screen?

Brower, macOS version, standard bug report stuff as well please.

**Comment by paulwakeford** [comment]
Well... now I can't reproduce the issue. Happy for you to close this and I'll reopen if I see it again. Thanks.
