### ISSUE TITLE
Feature Request: Activate DND when plugging in additional screen. 

### ISSUE THREAD

**Issue by conways-glider** [bdkjones/MuzzleApp#18]
I think a good addition would be to turn on Do Not Disturb when a second/additional screen is plugged in (like when one is giving a presentation).

**Comment by bdkjones** [comment]
This is already an option in System Preferences > Notifications.

**Comment by beep** [comment]
I believe the existing System Preference is for _mirroring_ to TVs and projectors, FWIW. If Muzzle could trigger DND when a second, non-mirrored screen’s available, that’d be _huge_ for me.

**Comment by bdkjones** [comment]
I mean...it's doable, but I'm not sure I see the use case. Why would you want notifications snuffed when an external display is connected?

-Bryan
