### ISSUE TITLE
Support Chrome screen sharing

### ISSUE THREAD

**Issue by GuiSim** [bdkjones/MuzzleApp#2]
Chrome extensions can record and share your screen.
Could Muzzle detect when this is happening and switch on Do Not Disturb?

One such application would be when screen sharing with https://appear.in

Thanks for the great app (and amazing website).

**Comment by bdkjones** [comment]
Should already work. Have you tried it?

**Comment by GuiSim** [comment]
Yes, Do Not Disturb was not activated.

Is it sufficient to verify if Do Not Disturb is toggled on?
![image](https://user-images.githubusercontent.com/2000390/27918440-fb09fb72-623c-11e7-96ba-01d980436ca1.png)

**Comment by GuiSim** [comment]
Okay, I did a few more tests.
If you record the full screen, it toggles DnD on.
If you only record a single app or tab, it doesn't activate it.

I think that makes sense since notifications probably don't appear when you only record a single app.

Sorry for the false alarm. Closing this.

**Comment by bdkjones** [comment]
Glad to hear!
