### ISSUE TITLE
Feature Request: Screenhero Support

### ISSUE THREAD

**Issue by joshprice** [bdkjones/MuzzleApp#20]

**Comment by bdkjones** [comment]
Have you verified that it doesn't work? What is screenhero?

**Comment by rosston** [comment]
[Screenhero](https://screenhero.com/) is yet another screensharing service, which eventually got bought by Slack, although it still works apart from Slack.

I just tested it, and Muzzle does in fact enable/disable DND correctly when starting/ending the screensharing session (using Muzzle 1.2 - Build 121 and Screenhero 2.3.12.0 on macOS 10.12.5).

**Comment by bdkjones** [comment]
Cool.

**Comment by joshprice** [comment]
Thanks all!
