### ISSUE TITLE
Request: On off button for muzzling during livestreaming

### ISSUE THREAD

**Issue by ghost** [bdkjones/MuzzleApp#23]
I love the auto detect idea, but all my screen sharing happens while livstreaming to the internet on YouTube and/or Twitch.tv. Would love the option to turn muzzle on and off for this.

Alternatively if you prefer the auto detect method, the livestreaming software I use is Wirecast.

Thanks!

**Comment by bdkjones** [comment]
Option-click the Notification Center button in the menu bar.
