### ISSUE TITLE
Notifications Still Show?

### ISSUE THREAD

**Issue by mattrmiller** [bdkjones/MuzzleApp#24]
In a Zoom meeting the other day, sharing my screen... I still saw notifications come in. is Muzzle just "hiding" these from screenshare, or is it suppose to turn on Do Not Disturb during this time?

My apologies if this is explained somewhere, I just could not find it.

- Cheers

**Comment by bdkjones** [comment]
Were they Chrome Notifications? Chrome has its own notifications UI; it doesn't use the system one.

**Comment by mattrmiller** [comment]
No, they were iMessage.

**Comment by bdkjones** [comment]
Is your Mac set to a locale other than English?

**Comment by mattrmiller** [comment]
No, English, latest Mac Sierra and Zoom... it has happened again since then. I am a software engineer, so let me know if you need any help debugging. It's a great app, and would love to get involved anyway I can.

**Comment by jonnymets** [comment]
I'm always seeing it not working while in a Zoom screen share. Simple install with English locale. Any ideas?

**Comment by robdecker** [comment]
Same here. Still see notifications while using Zoom.

**Comment by jydesign** [comment]
Same here, it seemed to stop working recently while using Zoom (version 4.1.11049.1024) - it's failing to turn DND on for me in both macOS High Sierra and Sierra.

**Comment by mseverini** [comment]
Piling on. I have the same issue. Works on google hangouts and slack, but not zoom.

**Comment by austinarbor** [comment]
Also not working for me with zoom.

**Comment by gee-forr** [comment]
Yeah - same here. It's just never worked for me.

**Comment by praveendhawan** [comment]
I had the same issue. 
Well, I was just trying out things and I can confirm that you need to start muzzle first and then get on the call. You will not get notifications now. Let me know if that works.

Probably a hint to debug for @bdkjones

**Comment by bdkjones** [comment]
See https://github.com/bdkjones/MuzzleApp/issues/51#issuecomment-725224916
