### ISSUE TITLE
Not working for me at all

### ISSUE THREAD

**Issue by datenreisender** [bdkjones/MuzzleApp#25]
Hi,

Muzzle does not work for me at all. I tried several screensharing apps (Google Hangout, Slack call, Screenhero) and during none of them did Muzzle turn on DND. Can I somehow help you to debug what goes wrong on my machine? 

Two things that may differ from your setup: I am using macOS set a German locale and my partition is set to be case sensitive.

Would be great if I could use Muzzle!

**Comment by bdkjones** [comment]
It's the German locale. Change it to English (US) and verify that it's working. The reason is that the Notification Center icon is named something different in German, obviously.

An interesting point; this will apply to all non-English locales. I'll see if I can work around it.

**Comment by datenreisender** [comment]
At least it would be nice if Muzzle would warn if it is unable to turn on DND. Of course it would be even nicer if it would be able to turn it on even for my locale. :-)

**Comment by datenreisender** [comment]
I can confirm that after changing the locale to English (and rebooting) Muzzle does work as I had hoped. But currently I am not willing to switch the locale permanently to get Muzzle working.

**Comment by bdkjones** [comment]
Well, yea, I'm not going to make you switch locales. I'll come up with a solution. That's what I do.

**Comment by bdkjones** [comment]
I have a version that I believe solves this issue. Please email me: bryan@codekitapp.com so I can send it to you and verify. Thanks.

**Comment by bdkjones** [comment]
This issue affects only macOS 10.13 and below and Muzzle 1.6 (released just now) no longer supports anything older than 10.14. Sorry this didn't get resolved!
