### ISSUE TITLE
Manual Muzzle Mode - Simple Off/On/Auto 

### ISSUE THREAD

**Issue by StephenInoue** [bdkjones/MuzzleApp#26]
I like the idea of Muzzle being in automode, but for those of us that do training videos and use screen capture programs like Screenflow or Camtasia where we need to control what pops up Muzzle is great, but in one section of my Wrike demo I need the iMessage notification to pop up, and it would be nice if I could simply turn off Muzzle as needed during that part of the demo.

**Comment by bdkjones** [comment]
The solution here is to quit the app and turn DND off manually when you want a notification to show. If I start adding all sorts of manual controls, things get very complicated very quickly. I definitely get the use-case, it's just that for 99% of people, this isn't a thing.
