### ISSUE TITLE
Feature Request: Manual Mode

### ISSUE THREAD

**Issue by danmandle** [bdkjones/MuzzleApp#27]
Not all screen sharing is done virtually. It would be awesome if one could enable/disable notifications with Muzzle similar to how it's done with [Caffeine](http://lightheadsw.com/caffeine/) or [Amphetamine](https://itunes.apple.com/us/app/amphetamine/id937984704) and toggle when clicked.

**Comment by bdkjones** [comment]
Option-click the Notification Center icon.

**Comment by danmandle** [comment]
TIL. Thanks.
