### ISSUE TITLE
Slack notifications popping up during screen-sharing on skype

### ISSUE THREAD

**Issue by yogodoshi** [bdkjones/MuzzleApp#29]
I'm using MacOS Sierra, Slack 2.7.1 and Skype 7.5.6 don't know what other info would be good to help you debug it.

Thanks for this great app btw :)

**Comment by bdkjones** [comment]
Yea, Muzzle can't always work with Skype right now because Microsoft is using an ancient, ancient approach to screensharing. I'm hoping their upcoming release will move to the modern API and this will solve the problem.

**Comment by yogodoshi** [comment]
@bdkjones got it but don't you think it would be nice to let people know about that in the "help" section? Or at least remove skype's logo from the homepage? :/

**Comment by bdkjones** [comment]
Yea, it's mentioned as a known issue in the release notes. As for the homepage: not trying to be sneaky; just a matter of Brian and I are super busy.
