### ISSUE TITLE
Feature request: Notification when muzzling

### ISSUE THREAD

**Issue by tylerclark** [bdkjones/MuzzleApp#30]
Would be cool to see it's actively working in the status bar

**Comment by bdkjones** [comment]
Not needed; the notification center icon dims when DND is on.

**Comment by tylerclark** [comment]
Ahhh nice! When coming out of a hangout, it does not turn off DND. Is there a way to automate that?

**Comment by bdkjones** [comment]
It should. Are you sharing your full screen in Google Hangouts? Are you using Chrome?

**Comment by tylerclark** [comment]
I go to meet.google.com, click start meeting, click share screen, i see the icon change color (nice), and then i end screen sharing, and then the hangout. still gray and in DND mode. I am using chrome 61, mac os 10.12.6

**Comment by tylerclark** [comment]
Any idea why it won't come out of DND?
