### ISSUE TITLE
Feature request: I wish there was a snooze button

### ISSUE THREAD

**Issue by jberk-godaddy** [bdkjones/MuzzleApp#34]
I love muzzle - however sometimes I want to use muzzle when I'm _not screensharing_.  Would be nice if I could click a button like 'snooze notifications' that would turn muzzle on for x amount of time.  Keep up the great work!

**Comment by bdkjones** [comment]
No need; just hold the option key while clicking the notification center icon in the menubar.

**Comment by jyboudreau** [comment]
Seems like the feature request is for a *timed* snooze. Doing the recommended action blocks notifications for a whole day. I use this, but then forget to turn if off when I do want notifications.

**Comment by jberk-godaddy** [comment]
Yes exactly! Same here I forget to turn it back on
