### ISSUE TITLE
Trigger on ClickShare session

### ISSUE THREAD

**Issue by andrewmassengale** [bdkjones/MuzzleApp#37]
We use ClickShare where I work, and it would be great if Muzzle could trigger when a ClickShare session starts.

https://www.barco.com/en/clickshare

**Comment by bdkjones** [comment]
Hmm. Dunno how these folks are handling their screen sharing, but they have to use Apple's modern APIs for Muzzle to work. You might have some luck using the "Activate DND when mirroring displays" option in System Preferences.
