### ISSUE TITLE
Hide menu bar icon

### ISSUE THREAD

**Issue by tobihagemann** [bdkjones/MuzzleApp#4]
I'm very picky about apps being in the menu bar. 😅 I'd like to have an option to hide the menu bar icon.

### Suggestion
- Add a checkmark to the preferences to hide the menu bar icon.
- If you open the app again (while it's running), it'll open the preferences.

Thank you for your great work! 👍

**Comment by stevenwaller** [comment]
Might be overkill, but you can use [https://www.macbartender.com/](https://www.macbartender.com/) to hide menu bar icons (and do other cool stuff).

**Comment by coolnalu** [comment]
+1 since this works in the background so would be nice if one can hide it.

**Comment by virtualrapha** [comment]
+1

**Comment by bdkjones** [comment]
Yea...I considered adding this. But the trouble is that I don't know of a good way to let people access the app if I obliterate the menubar icon. I could add a global hotkey combination, but no one's going to remember that.

And without the icon in the menubar, now you just get DND toggling on/off and you forget that you installed Muzzle a year ago and you're mystified. It's a tough situation, but I'm open to ideas.

**Comment by virtualrapha** [comment]
@bdkjones I've seen other apps solving that problem by basically making a standard window application with an optional menu bar icon. So even when the menu bar icon is hidden, if someone launches the application from the `Applications` folder, the window will re-appear.

**Comment by tobihagemann** [comment]
That's what I tried to suggest in my second point. :smile: If you open the app (not the initial launch but when it's already running), the preferences windows will appear. In that way, a user could show the menu bar icon again if he needs it.

I wouldn't worry too much about users forgetting that Muzzle is running. That's the responsibility of the user. :wink:

**Comment by bdkjones** [comment]
You'd be amazed at how poorly "that's the responsibility of the user" goes over in customer support responses. 

I like the Prefs window idea, though. I'll implement this for 1.3. Pushing 1.2 out tonight to resolve a crash on 10.11

**Comment by tobihagemann** [comment]
Oh yes, I totally know what you mean. I'm dealing with a lot of customer support as well. :joy: Thank you for considering this feature request! 👍

**Comment by bdkjones** [comment]
Implemented for 1.3, which should ship in a couple days.

**Comment by StephenInoue** [comment]
I'm using 1.2, but the ability to hide Muzzle works fine with BarTender - a great menu bar organizing app.

**Comment by bdkjones** [comment]
Implemented for the next release.
