### ISSUE TITLE
Error on launching Muzzle

### ISSUE THREAD

**Issue by chuckf** [bdkjones/MuzzleApp#42]
When I launch Muzzle, I get an error that reads:

"Muzzle failed to process a script properly and the app won't work. Relaunching may fix this. If it does not, please contact me."

Relaunching does not fix the issue, nor does a reboot (for a separate reason, but still..)

Running MacOS 10.13.5

**Comment by bdkjones** [comment]
Interesting. Try trashing the app and downloading a fresh copy. Make sure you move it to /Applications before launching it.

**Comment by chuckf** [comment]
Same issue after downloading the fresh copy and dropping it into applications.

**Comment by bdkjones** [comment]
Hmm. Nobody else has reported this problem, so it must be something specific to your Mac. What else is running on this machine?

**Comment by chuckf** [comment]
I have a few things running, but nothing else has changed outside of the upgrade to the latest versions of MacOS and Xcode. 

Muzzle has been running fine on this machine since near day 1 of the announcement of Muzzle.

**Comment by bdkjones** [comment]
I was never able to reproduce this behavior on High Sierra and Muzzle 1.6 (released just now) drops support for all versions of macOS before 10.14, so I'm closing this one. Sorry it was never solved!
