### ISSUE TITLE
Feature request: Stride

### ISSUE THREAD

**Issue by ismetanin** [bdkjones/MuzzleApp#43]
[Stride](https://www.stride.com) has screen sharing and it would be great to silence notifications during screen sharing.
I am happy to help with coding this, if this is a open collaboration type project.

**Comment by danielcompton** [comment]
Stride has merged with Slack now and is shutting down soonish, so this may not be necessary anymore?

**Comment by ismetanin** [comment]
@danielcompton You're right, it's not necessary now
