### ISSUE TITLE
Feature Request: Cisco Jabber

### ISSUE THREAD

**Issue by ryanmerolle** [bdkjones/MuzzleApp#49]
[Cisco Jabber](https://www.cisco.com/c/en/us/products/unified-communications/jabber-mac/index.html) is a communications app (voice, video, chat) that allows for full screen sharing.  It would be nice to include this in the MuzzleApp in the same way Slack and the other screen sharing apps are supported.

BTW, great app!  I appreciate you maintaining this project, and I recognize/understand this feature request may not be on anyone's priority list.

**Comment by bdkjones** [comment]
If it doesn’t currently work, that means they don’t use Apple’s official screensharing APIs and Muzzle can’t detect when the app starts screensharing.
