### ISSUE TITLE
Muzzle does not work properly on macOS Mojave

### ISSUE THREAD

**Issue by SteveIsles** [bdkjones/MuzzleApp#50]
On Mojave, when MuzzleApp activates or de-activates Do-Not-Disturb, it doesn't change the DND status but just causes the Notification sidebar to appear on the right.  Whatever API muzzle is using to make the change is not properly changing the switch.

**Comment by bdkjones** [comment]
Thanks! I'll take a look. What locale is your mac set to?

**Comment by SteveIsles** [comment]
Thanks!  Locale is English-US. (I'm in California)

**Comment by bdkjones** [comment]
And you have given Muzzle the proper access, right? Mojave has new limits on what apps can do without permission.

**Comment by SteveIsles** [comment]
Yes.  I had to give it permission in Accessibility, and I verified it in System Preferences.  I believe this should be easily verifiable if you had a Mac running Mojave to replicate.

**Comment by SteveIsles** [comment]
Also, the fact that it pops open the Notifications sidebar and doesn't close it I think is further "proof" that the API permission was granted, but maybe I'm wrong.

**Comment by kunalghate** [comment]
I have the same issue with Muzzle on Mojave. Hopefully it is a quick fix for you Bryan!

**Comment by bdkjones** [comment]
Yea. Mojave broke a bunch of stuff related to event posting in the quest for more security. 

Fortunately, I have over a decade of experience beating macOS in the face with a 2x4. I have a new approach and will have it implemented in a day or two.

**Comment by jsywulak** [comment]
Any update on this?

**Comment by bdkjones** [comment]
Yea. Muzzle 1.4 was released weeks ago to add support for Mojave.
