### ISSUE TITLE
Muzzle Not Activating - High Sierra or Mojave

### ISSUE THREAD

**Issue by EigenTheory** [bdkjones/MuzzleApp#51]
I was helping a colleague install MuzzleApp on their MacBook Pro with High Sierra and noticed it would not activate with Slack sharing, Zoom, or Skype. I know this was working before, not sure what or when it broke. I am also unable to get the app to activate DND on Mojave latest public, although I would expect that.

**Comment by bdkjones** [comment]
Which version of Muzzle are you running?

**Comment by EigenTheory** [comment]
v1.5 - build 304

**Comment by nbdmaw1** [comment]
I am having the same issue.  2017 MBPro running High Sierra with Muzzle 1.5 build 304

**Comment by jsywulak** [comment]
I'm having a similar issue on a 2015 MBP running Mojave with Muzzle 1.5. Was working fine before I upgraded to Mojave. Let me know if there's any way to pull logs or provide any other information.

**Comment by patrykkalinowski** [comment]
v15 build 304, Mojave 10.14

not working

**Comment by mroderick** [comment]
Also not working on Mojave 10.14.3 (18D109), with Muzzle v1.5, build 304.
Happy to help debug this

**Comment by EigenTheory** [comment]
Bump. Any updates?

**Comment by bdkjones** [comment]
There may have been changes in 10.14.3 that caused this. I’ll take a look this weekend.

**Comment by leos** [comment]
@bdkjones any chance of updates on this? Happy to help debug or troubleshoot.

**Comment by bdkjones** [comment]
Unfortunately, the next two weeks are jammed with family obligations for me. I’m hoping to get into this, but can’t promise anything until closer to the end of the month.

**Comment by mathieubrunpicard** [comment]
Same issue here. Sierre 10.12.6 (16G1114). Running on v1.5, build 304.

**Comment by jakobwesthoff** [comment]
Same issue here: Mojave 10.14.5 (18F203). Muzzle: 1.5 build 304.

It seems currently the app is not working :(

Are there any updates regarding this issue?

**Comment by mjabdulm** [comment]
Hi 

Any update? Does the app work on Mojave?

**Comment by bdkjones** [comment]
Yep. I’ve tested it on Mojave and it works fine. Please provide specific steps where you see Muzzle not working.

-Bryan

**Comment by mjabdulm** [comment]
Hi,

I just checked it. Here is my observations:

Zoom:

- When I start presenting, it enables DND
- When I stop presenting, it disables DND but the DND notification icon is
still grey(that caused the confusion)


Google Meet(replaced Hangouts):

- It neither diabsle nor enables the DND mode.

Thanks,
Abdul

**Comment by bdkjones** [comment]
Zoom added their own "silence system notifications while sharing desktop" option. However, Zoom is a dumpster fire of godawfulness (seriously—I dumped the binary and went through it) so the WAY that they change DND has two disadvantages:

1. It breaks completely on Big Sur.
2. It leaves the menubar icon out of sync with the state of DND because they're doing something sketchy behind macOS's back. Innocent developers (me) get blamed for Zoom's incompetence.
3. It undoes the toggling that Muzzle does and therefore Zoom and Muzzle cancel each other out, leaving you to think that Muzzle is broken. 

Muzzle 1.6 is out today and will now warn you to disable the relevant option in Zoom. I've tested Zoom on Mojave, Catalina, and Big Sur: Muzzle correctly detects screensharing and turns on DND. 

Finally, be sure you're actually SCREENSHARING. I get so many angry emails from people who think Muzzle kicks in when they merely start a call. Nobody can see your notifications until you share your screen, so Muzzle won't turn on DND until you Share. The. Screen.

**Comment by glrodasz** [comment]
@bdkjones I just noticed that disabling Zoom silence system does the trick with Muzzle 1.6, but when you stop sharing the screen the DND keeps on (Muzzle doesn't turn it off), so next time that you share the screen it will disable the DND, showing the notifications.

**Comment by bdkjones** [comment]
That’s not Muzzle. Muzzle looks at the state of DND before screensharing starts and restores whatever state was being used.

-Bryan

**Comment by glrodasz** [comment]
> That’s not Muzzle. Muzzle looks at the state of DND before screensharing starts and restores whatever state was being used.
> […](#)
> -Bryan
> On Nov 24, 2020, at 09:07, Guillermo Rodas ***@***.***> wrote: ﻿ @bdkjones I just noticed that disabling Zoom silence system does the trick with Muzzle 1.6, but when you stop sharing the screen the DND keeps on, so next time that you share the screen it will disable the DND, showing the notifications. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Maybe someone could help me to confirm this behavior but basically, I tested this:

* Zoom with the "Silence system notifications when sharing desktop" turned off and **without** Muzzle: I share and unshare my screen multiple times the DND was in its original state every time.

* Zoom with the "Silence system notifications when sharing desktop" turned off and **with** Muzzle: The first time that I shared the screen DND was turned on, but after unshare the screen it kept turned on. Then I share my screen again and DND was turned off. It is like when Muzzle is enabled it toggles DND every time that I share a screen in Zoom.

**Comment by acostalima** [comment]
> Zoom with the "Silence system notifications when sharing desktop" turned off and with Muzzle: The first time that I shared the screen DND was turned on, but after unshare the screen it kept turned on. Then I share my screen again and DND was turned off. It is like when Muzzle is enabled it toggles DND every time that I share a screen in Zoom.

I can confirm this behavior on my end as well! I'm on Catalina still by the way.
