### ISSUE TITLE
Menubar icon not properly hidden

### ISSUE THREAD

**Issue by r00b** [bdkjones/MuzzleApp#52]
If I select in settings to hide the menu bar icon, the icon will hide. However, when I restart my computer, the icon will be shown again in the menu bar, even though in settings the selection to show the menu bar icon is not checked.

**Comment by bdkjones** [comment]
Thanks, I’ll look into this.

**Comment by Leksat** [comment]
Just to confirm, I experience the same issue after build 304 `This update restores the "hide menu bar icon" option`. Also tried to completely re-install the app - does not help.

**Comment by bdkjones** [comment]
Yea, I’ll push an update soon to keep the setting after a restart.

**Comment by bdscharf** [comment]
Confirming that this issue still exists on macOS 10.14.1 Mojave and Muzzle 1.5 after a restart. Re-selecting and un-selecting the "hide" button in the preferences hides it again.

**Comment by jonathanbull** [comment]
Any update on this? I almost feel cheeky asking as Muzzle is otherwise perfect. Thanks for all your work on it @bdkjones.

**Comment by Leksat** [comment]
My current workaround: try to reboot as less as possible 😅

**Comment by elstgav** [comment]
Experiencing this on macOS 10.15.3 as well, with Muzzle 1.5

**Comment by flavorplus** [comment]
Yep same problem here

**Comment by acousticbiker** [comment]
Great work on Muzzle, Bryan! Confirming this is still an issue on 10.15.4. 

Also, in reappearing on the menubar, it doesn't seem to remember its location in the menubar relative to other menubar icons.

**Comment by bdkjones** [comment]
Well, let's just pretend that I didn't take two years to close this one out, shall we? Version 1.6 is out and fixes this. Good chat. See you out there.

**Comment by r00b** [comment]
💯 👍

**Comment by acousticbiker** [comment]
Better late than never! I’m hoping you came back to this to add Apple Silicone support?
