### ISSUE TITLE
Muzzle opening notifications bar instead of enabling DND during screen shares

### ISSUE THREAD

**Issue by embryoconcepts** [bdkjones/MuzzleApp#56]
Muzzle 1.5 build 304, MacOS Mojave 10.14.3, running RingCentral (Zoom)

Sometime in the last couple of weeks, instead of turning on DND, Muzzle is opening my notifications bar when I start screensharing, as well as no longer blocking individual notifications. Kind of the opposite of what I'm looking for. I've fully removed the app and reinstalled, and am still having the same issue. This is the first time this has happened in a couple of years, and I can't think of any system changes that occurred that could have triggered the issue.

**Comment by bdkjones** [comment]
Are you running the latest version of the app? Have you enabled any accessibility settings on your Mac?

**Comment by embryoconcepts** [comment]
Yes to both

**Comment by bdkjones** [comment]
Which accessibility options are configured on your Mac?

**Comment by embryoconcepts** [comment]
Sorry, misread your accessiblity question as "have you given Muzzle accessibility permissions" which I have. To answer your _actual_ question, I have not enabled any of the accessibility options.

**Comment by bdkjones** [comment]
Ok, can you post a screenshot of the about window for Muzzle and the about window for macOS?

**Comment by embryoconcepts** [comment]
![Screen Shot 2019-03-14 at 9 09 14 AM](https://user-images.githubusercontent.com/1554169/54359363-dd836700-4638-11e9-8f26-3f6bd0917f53.png)

**Comment by bdkjones** [comment]
This *should* be fixed in version 1.6, released just now. I tested Mojave specifically and didn't get this behavior to reproduce there.
