### ISSUE TITLE
Support for Airplay

### ISSUE THREAD

**Issue by foundinblank** [bdkjones/MuzzleApp#57]
I'm not sure Muzzle works when I'm screen sharing via Airplay to my Apple TV, I still see notifications (but sometimes I don't, but I'm not sure why). When looking at the website, I can see Muzzle supports Slack, Hangouts, etc., but can't tell if Muzzle supports Airplay or not.

**Comment by bdkjones** [comment]
Airplay is not screensharing. That’s “mirroring” and there is an option in system preferences > Notifications to turn on DND while mirroring.
