### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by joelharrison** [bdkjones/MuzzleApp#58]
I want everything to go away except for calendar reminders for my next meeting. Couldn't tell if this is by default or a 'feature request' –– LOVE your app!!!!

**Comment by meetbryce** [comment]
I would also pay for this feature.

I've more than once muted notifications and then ended up missing a meeting because I didn't get a calendar notification.

**Comment by bdkjones** [comment]
Yea, unfortunately there’s no way for me to do this. I can suppress all notifications or none, but for good security reasons it’s not possible to have an app say to the system, “tell me every notification that any app is going to post and I’ll decide which ones to allow after I scan them for sensitive information and upload that to my server so I can send it to the Russians.”
