### ISSUE TITLE
Check every few minutes if Muzzle needs to be disabled

### ISSUE THREAD

**Issue by danielcompton** [bdkjones/MuzzleApp#59]
Muzzle currently doesn't detect [Google Meet](https://github.com/bdkjones/MuzzleApp/issues/21) and other screensharing apps finishing the screensharing.

As a stopgap, would you consider adding a polling function where every few minutes Muzzle checks if it still needs to be active? I'm not sure if this would work with your current detection method though?

**Comment by bdkjones** [comment]
macOS changed the way they do a thing that Muzzle relies on and that caused the "fail to catch end" behavior. It should be resolved in version 1.6, out now.
