### ISSUE TITLE
Feature Request: WebEx Support

### ISSUE THREAD

**Issue by MeatMeSouthOfMarket** [bdkjones/MuzzleApp#6]
And that old fella, WebEx

https://www.webex.com/

**Comment by bdkjones** [comment]
Already works with it. Make sure you share the full screen. Partial screen sharing doesn't turn off notifications.

**Comment by MeatMeSouthOfMarket** [comment]
Great! I didn't see it in the icon list on the muzzle.com site and couldn't easily find a "feature" list. So what might need to happen with WebEx or Muzzle to support partial screen sharing? Perhaps some sort of flag in WebEx when it is sharing?

**Comment by bdkjones** [comment]
Mmm, well, with partial sharing you normally wouldn't worry about notifications because you're only sharing one window or a segment thereof—the notes aren't included in the shared area.
