### ISSUE TITLE
Feature Request: some app for Chinese most user need supported

### ISSUE THREAD

**Issue by iichaner** [bdkjones/MuzzleApp#72]
Zhumu, a Chinese version of zoom, is widely used in business communication. Many enterprises are using this software. If this software can be supported, it's great! Our company uses him every day, even for more than 20 hours a week.

In addition, Chinese enterprises like wechat (Tencent application) and Pinpin (Alibaba application) have the function of screen sharing. If they can support these Chinese applications, I believe they will have a great effect on your software promotion!

Hope to get your reply

Arvin

From Google Translate

**Comment by bdkjones** [comment]
Unfortunately, it’s not possible for me to test these apps. And while I don’t want to insult anyone or start a big political flamewar, there’s no way any Chinese software is going to touch my Mac. China’s government is simply not trustworthy and engages in a level of surveillance and manipulation that is intolerable to those of us in freer societies.

**Comment by iichaner** [comment]
Muzzle's design concept is simple and elegant. I'm sorry I missed it. I understand your concern very much. Thank you for your reply.

Chinese society is a huge and complex system, and it is also facing various challenges. I believe that this is also the helpless measure of the government.

Arvin

From Google Translate

**Comment by bdkjones** [comment]
Yep, no government is immune from criticism. That's for sure!
