### ISSUE TITLE
How do I uninstall Muzzle?

### ISSUE THREAD

**Issue by borosdenes** [bdkjones/MuzzleApp#75]
I gave Muzzle a try, although given by an ambiguous behaviour I experienced*, furthermore the concerns #62 gathers, I decided to uninstall it (via CleanMyMac X).

But today I've noted that through a Zoom call, when I shared my screen, DND was turned on automatically. The only reason I can come up with is that Muzzle left something somewhere, so that it keeps working partially. **Could you help me uninstall Muzzle, with restoring everything it modified?**

*The ambiguous behaviour I experienced was that DND wasn't switched consistently, moreover Muzzle made the top-right corner DND icon behave inconsistently (meaning it showed DND off when it was on, and the other way around).

**Comment by bdkjones** [comment]
This isn’t Muzzle. The latest version of Zoom includes an option to turn on DND when zoom calls start.

The “ambiguous behavior” you’re describing is a conflict between these two tools—both are trying to toggle the DND setting at various points and that leads to inconsistencies. If you use Muzzle, disable the Zoom option to turn on DND automatically.

**Comment by bdkjones** [comment]
Additionally, as I seem to have to explain at least 40 times per week: Muzzle activates DND when SCREENSHARING begins. 

It does not activate DND when you merely start a video call, as nobody can see your screen at that point. Folks misunderstand this and think the app is broken when it’s not.

**Comment by borosdenes** [comment]
I totally missed that Zoom feature, thank you so much for noting that (Zoom resets DND incorrectly w.r.t. top-right corner icon colouring) – turns out I can start using Muzzle once disabling that Zoom feature! 🎉 

And yea, I hear you about mere video calls, indeed I was asking about screensharing exclusively. Thanks again, keep up the good work!
