### ISSUE TITLE
Feature Request: Support for Microsoft Teams screen sharing

### ISSUE THREAD

**Issue by arope28** [bdkjones/MuzzleApp#76]
Microsoft Teams is becoming a replacement for Slack at some companies, so it would be nice if the MuzzleApp recognized when screen sharing is active in Microsoft Teams so it can automatically disable notifications.

**Comment by bdkjones** [comment]
When you share your screen using Microsoft teams, do you notice a lot of fan noise and high CPU usage, compared to other screen-sharing apps such as Zoom or Slack?

**Comment by Ikabodo** [comment]
Not OP, but I agree that adding teams would be very useful! 

And to answer your question, yes! When screen-sharing or in a meeting the fan starts and the CPU usage increases significantly.

**Comment by bdkjones** [comment]
Yea, so that's why Muzzle isn't working. There are two ways of screensharing: 

1) Take 30 screenshots per second and stitch them into a video.

2) Use Apple's official API to receive the contents of the screen buffer directly from the graphics card.

Teams is likely using (1), which is why the CPU gets hit hard and the fans come on. The first method is stupid-inefficient. The second method has almost no impact on resources at all. Muzzle is hooked into the second method and relies on kernel events to detect when screensharing begins and ends. If an app is just dumbly snapping 30 screenshots per second, Muzzle has no idea the screen is being shared.

Tell Microsoft to write better software.

**Comment by Ikabodo** [comment]
That’s really sounds bad. Microsoft do some weird things.

Are you sure though?

I saw there are settings in privacy options to allow teams the right to record the screen. So at least the Mac knows teams want to record the screen.

![CE0F8BD0-DED8-4327-B15B-EE681648EFDC](https://user-images.githubusercontent.com/7766890/84330221-1f29f700-ab87-11ea-8a56-3a78e7704a1b.png)

**Comment by bdkjones** [comment]
That's not the same thing. Any app that wants to take a screenshot in Catalina must have permission to do so. Even an app as simple as a color-picker tool. 

Catalina is a dumpster fire of security-overreach and the "have to grant permission for a color picker to tell what color a pixel is" is a great example of the stupidity of modern Apple, but that's a discussion for a different day. 

Hopefully some of this nonsense gets rolled back in 10.16, which should be announced in about two weeks. I wouldn't hold my breath on that, though.

**Comment by Ikabodo** [comment]
Sorry to poke this again. Not sure if this is relevant. But noticed this setting in teams recently, haven't seen it before. Does that mean Teams changed anything?

![Screenshot 2020-08-28 at 13 29 48](https://user-images.githubusercontent.com/7766890/91556255-b6a31880-e932-11ea-9c63-0ad4234b8799.png)

**Comment by bdkjones** [comment]
Unlikely. If Teams adopts Apple’s official screensharing API, Muzzle will work automatically.

**Comment by kjmci** [comment]
Came here to request the same thing, and now understand the reliance on the MacOS API so thanks for clarifying. I have seen the following comment on Microsoft's uservoice site for Teams: 

> Share video and audio during meetings is released on Windows. Mac support is now planned for CY20Q3.
> https://microsoftteams.uservoice.com/forums/555103-public/suggestions/32616083-share-system-audio-during-meetings

Crossing my fingers that this means they are adopting the appropriate API and Muzzle support will be subsequently enabled.

**Comment by bdkjones** [comment]
When they adopt the official screensharing API and stop melting people's CPUs, Muzzle will work automatically.
