### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by mattkaye** [bdkjones/MuzzleApp#77]
I've opened both Zoom and Webex teams. I see no indication from the icon or otherwise that this app is doing anything. How do I know if it's working?

Mac OS Catalina 10.15.5

**Comment by bdkjones** [comment]
Muzzle does nothing until you share your screen. Merely opening zoom has no effect. When Muzzle turns DND on, the Notification Center icon in the menubar will dim.

**Comment by mattkaye** [comment]
Ahh, gotcha. Thanks. One last question does it work for Webex Teams? It would be useful if you listed the clients that it does support in the FAQ. I didn't see that so if it's there my apologies. Thanks for this awesome little tool!
