### ISSUE TITLE
Do Not Disturb Left Enabled

### ISSUE THREAD

**Issue by orcutt989** [bdkjones/MuzzleApp#84]
I know the FAQ says Muzzle resets to whatever setting it had before, but the thing is I have verified that DND is not enabled.  I start sharing and then Muzzle turns on DND. Then when I quit screen sharing or quit out of Zoom completely DND is still enabled.  If i disable it and then do it again the same thing happens.  I'm not sure if this is a Big Sur bug or what. I have the Zoom setting disabled as well.

**Comment by bizob2828** [comment]
I've been hitting the same issue since upgrading to Big Sur

**Comment by zgosalvez** [comment]
I've been meaning to report this. I can confirm that this recently only happened after upgrading to Big Sur. I can't confirm for other video tools, but it's definitely happening with Google Meet.

**Comment by bdkjones** [comment]
Sigh. *Of course* Apple changed the exact tiny behavior I depend on between 11.0 and 11.0.1. I've just released Muzzle 1.7, which restores the correct behavior on macOS 11.0.1. Check for updates in Muzzle and you'll be all set.

**Comment by devnoname120** [comment]
Note that I've encountered this issue today on macOS 10.15.7, and Muzzle 1.7.

I will update macOS to see if this fixes it (it suppose it will).

**Comment by bizob2828** [comment]
thanks @bdkjones! 1.7.1 fixed my issue 🙏🏻

**Comment by stang** [comment]
Hi 👋 
I'm running macOS `10.15.6` and Muzzle `1.7`, and I'm having the same issue (cf: DND does not switch off once the meeting are over).

The _check update_ feature tells me that I'm using the latest version available. Is there any alternative solution that does not require upgrading macOS?

**Comment by bdkjones** [comment]
Not currently. The issue does not manifest on macOS 11.0.

I'll eventually fire up Catalina on an old Mac and see what's going on, but my advice is to keep your Mac up-to-date. Big Sur is pretty good.

**Comment by stang** [comment]
thanks for the quick reply @bdkjones!

Unfortunately, I'm using a corporate device where I have no control over the os upgrade. It might come at some point...

Meanwhile, could an older version of Muzzle be a workaround for my issue? If so, would you mind sharing a link to download an older release?

cheers!
