### ISSUE TITLE
When triggered, it will open up Notification Center first before disabling the notification

### ISSUE THREAD

**Issue by zhigang1992** [bdkjones/MuzzleApp#89]
It might only be a problem on Big Sur.

**Comment by karlhorky** [comment]
This also appears for me on Big Sur - macOS 11.1 (20C69) and Muzzle 1.7.

**Comment by cntlsn** [comment]
I'm on:
* MacOs Big Sur 11.2
* Muzzle v1.7 - Build 405

This happens to me with:
* Google Meet on Firefox 78.7.0esr
* Google Meet on Chrome 88.0.4324.150
* BlueJeans Version 2.26.0 (2.26.0.289)

Also, Notification Center is also displayed when screen sharing has stopped.

**Comment by bruno-robert** [comment]
I also have this issue

**OS:**  BigSur - macOS 11.2.3 (20D91) 
**Muzzle version:** 1.7

Apps causing notification center to be displayed:
- Zoom 5.4.9 (59931.0110)
- Discord 0.0.262 (0.0.262)


Notification center is opened when screen sharing is started and when screen sharing is stopped.

This effectively shows all my notifications to anyone watching my screen sharing. Ironically this is the opposite effect I am trying to achieve 😄

**Comment by bleonard** [comment]
Similar experience here on 11.2.3
It starts opens the sidebar when I choose a screen but before presenting on Google Meet.
I verified this does not happen if Muzzle is not running.

**Comment by bdkjones** [comment]
This is solved. It took so long because the issue was intermittent—I couldn't get Big Sur to reliably do it, which made finding a fix a very long process.

**Comment by bleonard** [comment]
It looks good. Thank you!
