### ISSUE TITLE
Muzzle not toggling DND in macOS 11.4

### ISSUE THREAD

**Issue by orcutt989** [bdkjones/MuzzleApp#94]
Title says it all! Since I upgraded to 11.14 Muzzle no longer toggles DND when screen sharing.  I tried reinstalling but that did not seem to fix it.

**Comment by bdkjones** [comment]
I think you mean 11.4? 

I'm unable to reproduce this issue; I just tested here on 11.4 and Muzzle correctly toggled DND when I started sharing my screen in Zoom. What service are you using to do the screen sharing?

**Comment by orcutt989** [comment]
Oops my bad! Yeah seems to be working now! Not sure what happened. Yep was using zoom! Thanks for the help!
