### ISSUE TITLE
Menu bar preferences not popping up

### ISSUE THREAD

**Issue by Nezteb** [bdkjones/MuzzleApp#95]
Video demo: https://user-images.githubusercontent.com/3588798/122285915-e2d55900-ceb4-11eb-8c2d-a4abcaee92e4.mp4

macOS Big Sur: Version 11.4

I've already allowed accessibility access for Muzzle. I even restarted my computer. I don't get any errors that I can see.

**Comment by RobVanGroenewoud** [comment]
Same problem here.
macOS Catalina 10.15.7 (19H1217)
Muzzle 1.8 - build 416

**Comment by dseifert** [comment]
Same here, too. MacOS Big Sur 11.4, Muzzle 1.8 Build 416. Removing (including files in ~/Library) and redownloading made no difference.

**Comment by bdkjones** [comment]
This is resolved in 1.9, which is out now. Thanks guys.

**Comment by Nezteb** [comment]
![photo_2021-06-21_15-27-19](https://user-images.githubusercontent.com/3588798/122823596-2eb54300-d2a5-11eb-9bf8-3bb86ab16b02.jpg)

I love the candor of the release notes. Can confirm this issue has resolved with version 1.9. Thanks Bryan!
