### ISSUE TITLE
Feature Request: Support macOS Monterey's Focus Modes

### ISSUE THREAD

**Issue by byount** [bdkjones/MuzzleApp#98]
If Apple is supplying a proper API for the new Focus Modes feature in macOS 12 Monterey, it would be great to be able to select a mode such as "Meetings" or "Work" for Muzzle to trigger in addition to the standard "Do Not Disturb".

**Comment by bdkjones** [comment]
Agreed! We’ll see what Apple provides.

**Comment by adib** [comment]
In any case, there is a focus mode action in Shortcuts.  Maybe run a shortcut to change focus mode?


Also SiriKit can [_query_ the user's focus status](https://developer.apple.com/forums/thread/682143?answerId=678333022#678333022).

**Comment by bdkjones** [comment]
It turns out Muzzle is no longer necessary on Monterey. Five years later, Apple finally got around to sherlocking it. This options used to be just "when mirroring", but now includes "or sharing":

<img width="668" alt="Screen Shot 2021-11-30 at 23 34 07" src="https://user-images.githubusercontent.com/926566/144191592-9f43f2c6-1ea9-466d-80fa-57faffc36518.png">

**Comment by karlhorky** [comment]
Amazing, thanks for the update @bdkjones !! 🙌

**Comment by acousticbiker** [comment]
> It turns out Muzzle is no longer necessary on Monterey. Five years later, Apple finally got around to sherlocking it. This options used to be just "when mirroring", but now includes "or sharing":
> 
> <img alt="Screen Shot 2021-11-30 at 23 34 07" width="668" src="https://user-images.githubusercontent.com/926566/144191592-9f43f2c6-1ea9-466d-80fa-57faffc36518.png">

Thanks for this update - a few questions:

- Given this setting is under 'Notifications' and not 'Focus', is it safe to assume it's working during a call even though DND doesn't indicate as being on (which was the case with Muzzle)?
- Given [Teams doesn't appear to use Apple's official API for screen sharing](https://github.com/bdkjones/MuzzleApp/issues/76), is it also safe to assume this function doesn't work for Teams? 
- If so, are there other apps which don't use the official API?

**Comment by karlhorky** [comment]
> * Given this setting is under 'Notifications' and not 'Focus', is it safe to assume it's working during a call even though DND doesn't indicate as being on (which was the case with Muzzle)?

It does work like you described, at least on Zoom screen sharing. No notifications, but also no DND indicator / Focus mode.

Would be interested to see if Teams also works like this!

**Comment by Nick-Gatti** [comment]
> It turns out Muzzle is no longer necessary on Monterey. Five years later, Apple finally got around to sherlocking it. This options used to be just "when mirroring", but now includes "or sharing":
> 
> <img alt="Screen Shot 2021-11-30 at 23 34 07" width="668" src="https://user-images.githubusercontent.com/926566/144191592-9f43f2c6-1ea9-466d-80fa-57faffc36518.png">

I wouldn't go as far as saying "Unnecessary". I have a DisplayLink dock that requires screen mirroring so I need to have this on to display notifications at all.
